version: '3.6'
services:
  new-years-functions:
    container_name: new-years-functions
    image: 'haydenbr/new-years-functions:0.0.3-dev'
    volumes:
      - './new-years-functions/common/src:/home/site/wwwroot/common/src'
      - './new-years-functions/hello/src:/home/site/wwwroot/hello/src'
      - './new-years-functions/quote/src:/home/site/wwwroot/quote/src'
    ports:
      - '3100:80'
    networks:
      - new-years-functions
networks:
  new-years-functions: null
